name: dorm_ios
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  font_awesome_flutter: ^10.7.0
  flutter_screenutil: any
  http: any
  shared_preferences: ^2.2.2
  dio: ^5.4.0
  image_picker: ^1.0.7
  file_picker: ^6.1.1 
  audioplayers: ^6.4.0
  intl: ^0.18.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  webview_flutter: ^4.4.1
  url_launcher: ^6.2.5
  http_parser: ^4.0.2
  cupertino_icons: ^1.0.8
  flutter_image_slideshow: ^0.1.4
  animate_do: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/dorm.png
    - assets/student_research.png
    - assets/logo.png
    - assets/dorm_background.png
    - assets/chatbot.png
    - assets/avatar.png
    - assets/audio/notification.mp3
    - assets/banner.png
    - assets/banner2.png
    - assets/banner3.png
    - assets/LoginPic1.png
    - assets/LoginPic2.png
    - assets/12.png

  plugin:
    platforms:
      android:
        default_package: file_picker
      ios:
        default_package: file_picker